name: stanchat
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.1+48

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  google_maps_flutter: ^2.12.1
  geolocator: ^14.0.0
  intl: ^0.20.2
  file_picker: ^10.0.0
  permission_handler: ^12.0.0+1
  path: ^1.9.1
  flutter_svg: ^2.0.17
  provider: ^6.1.4
  get_it: ^8.0.3
  dio: ^5.8.0+1
  just_audio: ^0.9.37
  flutter_contacts: ^1.1.9+2
  socket_io_client: ^3.1.2
  connectivity_plus: ^6.1.4
  package_info_plus: ^8.3.0
  status_view: ^0.0.2
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.5
  video_player: ^2.9.5
  video_trimmer: ^5.0.0
  syncfusion_flutter_pdf: ^30.1.37
  syncfusion_flutter_pdfviewer: ^30.1.37
  device_info_plus: ^11.1.0
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1
  flutter_secure_storage: ^9.2.4
  flutter_hooks: ^0.21.2
  flutter_inappwebview: ^6.0.0
  # Firebase
  firebase_core: ^2.32.0
  firebase_analytics: ^10.10.7
  # OneSignal
  onesignal_flutter: ^5.3.3
  uuid: ^4.5.1
  flutter_local_notifications: ^19.3.0
  flutter_webrtc: ^1.0.0
  peerdart: ^0.5.6
  giphy_get: ^3.5.6
  share_plus: ^11.0.0
  # Device sound profile and vibration
  audioplayers: ^6.1.0
  flutter_html: ^3.0.0-beta.2
  geocoding: ^4.0.0
  google_places_flutter: ^2.1.0
  http: ^1.2.2
  get_thumbnail_video: ^0.7.0
  video_compress: ^3.1.4
  record: ^6.1.2

dependency_overrides:
  flutter_webrtc: ^0.12.2
  # light_compressor:
  #   git:
  #     url: https://github.com/packages-primocys/light_compressor-2.2.0.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/call/
    - assets/images/call_history/
    - assets/flags/
    - assets/images/svg/
    - assets/images/footer/
    - assets/audio/
    - assets/map/
    - assets/data/country_codes.json

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
    - family: PoppinsBold
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
    - family: PoppinsMedium
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
    - family: PoppinsSemibold
      fonts:
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
    - family: JostSemibold
      fonts:
        - asset: assets/fonts/jost/Jost-SemiBold.ttf
    - family: vietnam
      fonts:
        - asset: assets/fonts/vietnam/BeVietnamPro-Regular.ttf
    - family: brittany
      fonts:
        - asset: assets/fonts/brittany/BrittanySignatureScript.ttf
    - family: lexend
      fonts:
        - asset: assets/fonts/Lexend/Lexend-Regular.ttf
